### ISSUE TITLE
Add color scheme for text editor

### ISSUE THREAD

**Issue by appleparan** [sublee/sublette#2] opened 2019-06-19 12:43 UTC
Text editor color schemes seems to be quite long term project (there are too many things to consider), but it would be grateful if a text editor such as VS code have this color scheme.

**Comment by sublee** [comment] 2019-06-19 12:55
I'm creating configurations for the tools I use. The problem is that usually, I don't use a GUI text editor. Anyways, I'm trying to create a configuration for IntelliJ, but perhaps I'll miss sensitive details because I'm not familiar to it.

Maybe it would be better to write `CONTRIBUTING.md` for GUI text editors, instead of creating configurations myself.

**Comment by sublee** [comment] 2019-06-19 17:08
I just released [a configuration for PyCharm or IntelliJ IDEA](https://github.com/sublee/sublette/tree/master/configs/IntelliJ). Try it if you use one of those editors.

I close this issue because now Sublette has a configuration for a GUI text editor.

**Closed as completed by sublee** 2019-06-19 17:08 UTC
Labels: config
